"""init

Revision ID: 37343374b2ed
Revises: b8a4eca04452
Create Date: 2020-08-26 16:49:11.244396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37343374b2ed'
down_revision = 'b8a4eca04452'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
